[build]
  command = "yarn generate"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.18.1"
  # Set production flag for build
  PRODUCTION = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Global headers for all files
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Range"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    
# Specific headers for parquet files
[[headers]]
  for = "*.parquet"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Range"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0" 